# Generated by Django 2.2.2 on 2019-06-20 01:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='resources.Client'),
        ),
        migrations.AlterField(
            model_name='location',
            name='bookings',
            field=models.ManyToManyField(related_name='locations', to='resources.Booking'),
        ),
    ]
